### ISSUE TITLE
Tile Not Working

### ISSUE THREAD

**Issue by ThePunish3r** [KurtSanders/STAmbientWeather#1]
![capture](https://user-images.githubusercontent.com/44322970/47258689-63253100-d464-11e8-9dc0-735ead3e17c5.JPG)

Kurt - Great application, I love this integration.  Thanks for writing this and publishing it.

I checked the logging within the IDE and the data is being collected correctly.  The outdoor temperature displays correctly on the My Home screen but when I look at the tile I get "Something's Wrong" error message.  Hopefully the screen capture is attached.  Any suggestions for trying to fix this?

**Comment by KurtSanders** [comment]
Thanks...are you using an android based client for mobile?  I think I've seen that error on non iPhone ST client...

**Comment by ThePunish3r** [comment]
Yes, Android smartthings app.

**Comment by KurtSanders** [comment]
For some reason, this app does not display on Android SmartThings client.  I imagine that it could be the preferences section which works perfectly on iOS SmartThings.  Since I do not have an Android ST device, I cannot test that assumption.  Sorry.
