### ISSUE TITLE
Hubitat Driver Import URL contains the code, not URL

### ISSUE THREAD

**Issue by doctorkb** [KurtSanders/STAmbientWeather#12]
Drivers | Ambient Weather Station | Raw Drivers Code Link

The file linked here contains the full code repeated in "importUrl" field, which generates an error in Hubitat.

**Comment by KurtSanders** [comment]
I will update when I return from vacation next week

**Comment by KurtSanders** [comment]
Thank you for identifying the repeated code block I inadvertently added in the last upload to github.  I have removed it and reloaded to the repository.

**Comment by doctorkb** [comment]
Thanks!  Looks good.
