### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by doctorkb** [KurtSanders/STAmbientWeather#13]
```
app:7062019-11-17 14:56:07.713 errorjava.util.ConcurrentModificationException: null on line 1526 (autoScheduleHandler)
app:7062019-11-17 14:56:07.708 infobaroUnitsDisplay 		= mmHg
app:7062019-11-17 14:56:07.705 infomeasureUnitsDisplay 	= mm
app:7062019-11-17 14:56:07.701 infowindUnitsDisplay 		= kph
app:7062019-11-17 14:56:07.698 infotempUnitsDisplay 		= °C
app:7062019-11-17 14:56:07.689 infoProcessing Ambient Weather data returned from AmbientStationData)
app:7062019-11-17 14:56:07.686 debughttpget resp status = 200
app:7062019-11-17 14:56:07.678 infoSUCCESS: AmbientStationData successfully updated for runID: 7911
```

This is on Hubitat 2.1.6.118.  The device never gets an update, when it is manually requested, this is logged:
```
dev:6112019-11-17 14:55:10.942 errorjava.lang.NullPointerException: Cannot invoke method refresh() on null object on line 501 (refresh)
dev:6112019-11-17 14:55:10.839 infoUser requested a 'Manual Refresh' from Ambient Weather Station device, sending refresh() request to parent smartApp
```

**Comment by KurtSanders** [comment]
I will investigate when I return from vacation next week.

**Comment by doctorkb** [comment]
Sounds good, thanks!  I'm excited about this app as it looks much better than the other one that had been floating around...

**Comment by KurtSanders** [comment]
Sorry for the error, let's try this again.  Seems like I inadvertently duplicated some code in the Ambient Weather Station driver code.  I have a new [uploaded driver file](https://raw.githubusercontent.com/KurtSanders/STAmbientWeather/master/hubitat/drivers/ambient-weather-station.driver) for your testing at:

https://raw.githubusercontent.com/KurtSanders/STAmbientWeather/master/hubitat/drivers/ambient-weather-station.driver

**Comment by doctorkb** [comment]
I don't think it was tied to the Driver code... I had fixed that in my local copy (though I did also take your updated code in case I missed something).  Still getting this:

```
app:7372019-11-23 12:38:24.161 errorjava.util.ConcurrentModificationException: null on line 1526 (autoScheduleHandler)
app:7372019-11-23 12:38:23.947 infoSUCCESS: AmbientStationData successfully updated for runID: 3402
app:7372019-11-23 12:38:23.897 infoSUCCESS: Retry AmbientStationData re-attempt #17 for runID: 3402
app:7372019-11-23 12:38:23.276 infoExecuting Retry AmbientStationData re-attempt #17 for RunID: 3402
app:7372019-11-23 12:38:23.148 infoAmbientStationData Time difference is 23991 secs between last execution
app:7372019-11-23 12:38:23.145 infoStart: AmbientStationData runID: 3402 at 12:38:23 PM
app:7372019-11-23 12:38:23.133 infoExecuting full ambientWeatherStation routine runID: 3402
app:7372019-11-23 12:38:23.116 infoHubitat Main (#3402) Section: Executing Ambient Weather Station API's for: 'Greenough Landing'
app:7372019-11-23 12:38:23.098 infoExecuting Cron Schedule runID: 3402 every 5 min(s)
```

That's in the app's log.

**Comment by KurtSanders** [comment]
Dear @doctorkb, 

Sorry you are having issues.  I am scratching my head on that error!  

How about I try installing your weather stations API Key to see what errors I receive on my hubitat log and debug the code.  I will delete the key after we fix the error and determine what is causing it. 
 Send your API key privately to my email at  kurt@kurtsanders.com 

Here is what my APP log shows for my weather station.  

```
app:72019-11-24 04:44:19.027 am infoSUCCESS: AmbientStationData successfully updated for runID: 9802
app:72019-11-24 04:44:17.882 am infoAmbientStationData Time difference is 120 secs between last execution
app:72019-11-24 04:44:17.879 am infoStart: AmbientStationData runID: 9802 at 04:44:17 AM
app:72019-11-24 04:44:17.866 am infoExecuting full ambientWeatherStation routine runID: 9802
app:72019-11-24 04:44:17.863 am infoHubitat Main (#9802) Section: Executing Ambient Weather Station API's for: 'TimberRidge'
app:72019-11-24 04:44:17.858 am infoDevice: 'Refresh ALL'
```

**Comment by KurtSanders** [comment]
I have uploaded a [new bug fix version](https://raw.githubusercontent.com/KurtSanders/STAmbientWeather/master/hubitat/apps/ambient-weather-station.app) for you to import into the Hubitat’s Ambient Weather Station APP and save it.  Then if you want to manually select a refresh, you can do that from any of your two devices.   

_The error that I identified with your logging information/screen shots, was that when non Imperial (US) units of measurement were selected in the App’s preferences, the imperial -> metric conversion routines were encountering a 'concurrent MAP update error', which was a new issue for me on the Hubitat development platform_.  

This is not a problem on SmartThings version, go figure?  I’m a SmartThings developer by heart and have been trying to convert to Hubitat.

This took me a few hours to eliminate.   I hope this updated version works for your weather station in Canada.  Thanks for being patient and we love the Canadians!
