### ISSUE TITLE
ST app tile missing most values

### ISSUE THREAD

**Issue by elkstreet** [KurtSanders/STAmbientWeather#19]
I've been using your Smart App+Handlers with success. I just updated to your latest Smart App and handlers and am having a problem. When I open the Weather Console tile in the ST App, I only see temperature and humidity. Gone are the illuminance and all other values. When I look at the history, I am able to show any of the values properly. If I try to create an automation and try to select a status from the weather console, only temp and humidity are available.

I have tried removing the devices, removing the device handlers, and removing the smart app. I also removed and reinstalled in the IDE but no luck. What am I missing?

**Comment by KurtSanders** [comment]
Sorry to hear, hopefully we can solve this.  

Are you using the classic ST mobile device or the new?  I can only test/support using the classic ST iOS mobile client at this point as I have yet to migrate all my home automations to the new ST client.

Can you send me your Ambient Weather API key so I can **temporarily** install in my ST and test what might be happening with your model/configuration of Weather Station.

Please email me at kurt at kurtsanders dot com (Email format of course).,
