### ISSUE TITLE
 java.lang.NullPointerException 

### ISSUE THREAD

**Issue by jeffp1105** [KurtSanders/STAmbientWeather#2]
I'm having the same issue as ThePunish3r was on android.  I get a java.lang.NullPointerException but can't figure out from what line of code.

I understand you don't have Android, but am willing to try things out on my end if you have suggestions. Attached is a log file with all logging turned on.
![screen shot 2018-11-20 at 10 22 45 pm](https://user-images.githubusercontent.com/44684349/48820604-e6130300-ed12-11e8-89cb-cd26b8a38081.jpg)

**Comment by KurtSanders** [comment]
I revised the program logic to verify that **Last Rain Date** data was being supplied by the Ambient Weather API.  Selected Ambient weather stations may not provide this expected data, and therefore if the weather station does not, it is replaced with a value of 'N/A'.   

Please update the Ambient SmartApp to latest V1.06 release!  

_Let me know if this corrects your specific error reported above._

**Comment by jeffp1105** [comment]
Hi Kurt,

The java error is now gone and the temperature now appears on the device list.  No other errors in live logging. However, the tile still errors out on my android SmartThings Classic app.  I'm not a Smartthings guru so not sure where to look for errors in the actual tile rendering.  I've attached phone screen shots.  Not sure where to head next.

Thanks again,
Jeff
![screenshot_20181121-085101_smartthings](https://user-images.githubusercontent.com/44684349/48852681-20a88a00-ed6b-11e8-8011-171b791a8128.jpg)
![screenshot_20181121-085110_smartthings](https://user-images.githubusercontent.com/44684349/48852682-20a88a00-ed6b-11e8-8875-90d9463ec2b9.jpg)
![screenshot_20181121-085123_smartthings](https://user-images.githubusercontent.com/44684349/48852683-20a88a00-ed6b-11e8-9b56-f1195f9aa2b4.jpg)

**Comment by KurtSanders** [comment]
I think I will have to work on a separate version compatible with Android o/s which will involve a new Smart App and companion DTH.  This single DTH version has a extensive preference section which I think is incompatible with the Android ST client (which is not my fault...)

**Comment by jeffp1105** [comment]
Thanks for the update. Completely understand.  The current version is great
for use with IFTTT because it lets me grab all the miscellaneous parameters
from Ambient that are not readily . For me, the tile was a nice-to-have.

Thanks for the hard work on this.
Jeff

*Jeff Posner*
*2938 Casalon Circle*
*Superior, CO 80027*
Home: 703-929-3736
Work: 202-794-4366

**Comment by KurtSanders** [comment]
Dear Jeff,

I have a V2 version of Ambient Weather Reporter V2 for you to test on your Android device.  It requires a SmartApp Service Manager and the new V2 Device Handler.  I have the updated readme in the BETA branch and would like you to test to see if it works and displays.

It can be installed along side of your V1 tile, so do NOT delete your working V1 device handler until we get this fully tested.

Here is the link to the beta branch and detailed instructions.

https://github.com/KurtSanders/STAmbientWeather/tree/beta <https://github.com/KurtSanders/STAmbientWeather/tree/beta> 


¸¸.•*¨*•*´¨)
¸.•´¸.•*´¨) ¸.•*¨)
(¸.•´ (¸.•` ¤ 

Kurt Sanders
2485 Ridge Road
Xenia, Ohio 45385
+1937-723-0010
