### ISSUE TITLE
Action Tile Show KPH

### ISSUE THREAD

**Issue by pwrboatfan** [KurtSanders/STAmbientWeather#22]
Hello, I have updated in GitHUB to latest version, however, on the Actiontiles it is showing wind speed in KPH.  Can this be changed to MPH?  In the smartapp in ST it is showing MPH.
![image](https://user-images.githubusercontent.com/61127305/87059965-8e6b2900-c1cf-11ea-963b-1a51fd15684c.png)

![image](https://user-images.githubusercontent.com/61127305/87060620-5ca69200-c1d0-11ea-87a1-82215e866a75.png)

![image](https://user-images.githubusercontent.com/61127305/87060996-cd4dae80-c1d0-11ea-8151-81c2e0916683.png)

**Comment by KurtSanders** [comment]
This same KPH units is displaying on the OEM SmartThings SmartWeather DTH even though the mobile ST client shows MPH..  I will send a support ticket to ActionTiles for explanation.  This was not occuring months ago, I did not notice until you reported.  I wonder what their explanation will be!
![2020-07-09_13-28-46](https://user-images.githubusercontent.com/12133562/87073520-87521400-c1eb-11ea-86e3-14f45fc87460.jpg)
![IMG_F75AFE3AC15C-1](https://user-images.githubusercontent.com/12133562/87073537-8de08b80-c1eb-11ea-8b98-f4209363cea5.jpg)

**Comment by pwrboatfan** [comment]
Thanks!  Yeah it changed about a month ago or at least when I noticed it.

Sent from my iPhone
________________________________

**Comment by KurtSanders** [comment]
ActionTiles Support Desk confirmed the UNITS issue is in their platform code, and a fix in in the works!

![image](https://user-images.githubusercontent.com/12133562/87076389-af437680-c1ef-11ea-811a-b8c5a5a2149f.png)

**Comment by pwrboatfan** [comment]
Great!  Thanks for the quick response!

Sent from my iPhone
________________________________

**Comment by KurtSanders** [comment]
This issue has been fixed by ActionTiles and verified below.

![2020-07-12_17-21-01](https://user-images.githubusercontent.com/12133562/87256983-32b9cd80-c465-11ea-88fe-6b88a240f1f6.jpg)

**Comment by pwrboatfan** [comment]
Great!  Thanks for the help!!!!

Sent from my iPhone
________________________________
