### ISSUE TITLE
Channel 1 battery

### ISSUE THREAD

**Issue by mapallatroni** [KurtSanders/STAmbientWeather#23]
I have a WS-50 with 4 temperature sensors, no weather station.   Everything seems to work fine with the exception that SmartThings does not see the battery for the sensor on channel 1.  It does not even show as a property to display.

Thanks.

**Comment by KurtSanders** [comment]
I do not support any of my custom SmartThings SmartApps issues any longer due to their new buggy mobile client having so many unresolved issues on so many levels.  

If you have Hubitat, you will find that developers end user SmartApps performs so much better!  Sorry!

**Comment by higsonhs** [comment]
Thanks so much!!  I’ll grab myself one of those!  I appreciate it very
much!
