### ISSUE TITLE
v6 SmartApp issues

### ISSUE THREAD

**Issue by seattleandrew** [KurtSanders/STAmbientWeather#24]
I know you've been frustrated by the new app and if you are still working on the smartthings support I would appreciate your help.

I updated my SmartApp and DTH (from V3!) today and tried starting new to get my PWS setup in smartthings. I made sure to closely follow the instructions for setting up a new installation (I deleted all the old devices, DTH and SmartApp).

I ensured that the API key was entered correctly and the smartapp confirmed it.

I am able to find my PWS although the name adds "null" to the end of it, I confirmed this by changing the device name in AmbientWeather. So my PWS is "HootervilleRd" but in the smartapp it labels it as "HootervilleRdnull".

When I tap "done" it goes to a blank page.

Here's the output from the smartthings live logging.
------------------------------------
78dc7896-f4c6-4719-b90b-1610fcae81f9 5:20:43 PM: debug Ignore invalid reports
78dc7896-f4c6-4719-b90b-1610fcae81f9 5:20:43 PM: debug levelEventHandle - currentLevel: 100 lastLevel: 100
78dc7896-f4c6-4719-b90b-1610fcae81f9 5:20:43 PM: debug attr: 8, value: 00, descValue: 0, FYRTUR block-out roller blind
78dc7896-f4c6-4719-b90b-1610fcae81f9 5:20:43 PM: debug description:- read attr - raw: EB4A0101020808002000, dni: EB4A, endpoint: 01, cluster: 0102, size: 8, attrId: 0008, result: success, encoding: 20, value: 00
a6ce7a7f-817f-4862-a6f8-59a12b05a435 5:20:40 PM: debug Parse returned [:]
a6ce7a7f-817f-4862-a6f8-59a12b05a435 5:20:40 PM: debug description: catchall: 0104 0020 05 01 0000 00 9887 01 00 0000 00 01
5:20:40 PM: debug description: catchall: 0104 0020 05 01 0000 00 9887 01 00 0000 00 01
**4c689e45-5495-4884-9c79-51a8fddf53b7 5:20:40 PM: error groovy.lang.GroovyRuntimeException: Ambiguous method overloading for method java.util.ArrayList#getAt.
Cannot resolve which method to invoke for [null] due to overlapping prototypes between:
[interface groovy.lang.Range]
[interface java.util.Collection] @line 224 (optionsPage)**
cc8c5ff1-5f58-43f5-9622-0e6587f6f57b 5:20:37 PM: debug healthPoll()
4c689e45-5495-4884-9c79-51a8fddf53b7 5:20:36 PM: debug The Ambient Weather API being used is: REDACTED
4c689e45-5495-4884-9c79-51a8fddf53b7 5:20:29 PM: debug AmbientStationData Time Difference is 0 secs between runs
4c689e45-5495-4884-9c79-51a8fddf53b7 5:20:29 PM: info Start: AmbientStationData runID: 0 at 05:20:29 PM
4c689e45-5495-4884-9c79-51a8fddf53b7 5:20:29 PM: debug *NEW* Ambient Weather API = REDACTED
a1c077da-6008-40f2-b7b1-a517a6b6df9f 5:20:28 PM: debug parsed event: [name:atmosphericPressure, value:101.1719, unit:kPa]
a1c077da-6008-40f2-b7b1-a517a6b6df9f 5:20:28 PM: debug description: read attr - raw: A2620104030C20002207700F, dni: A262, endpoint: 01, cluster: 0403, size: 12, attrId: 0020, result: success, encoding: 22, value: 0f7007
a1c077da-6008-40f2-b7b1-a517a6b6df9f 5:20:27 PM: debug parsed event: [name:temperature, value:79.3, unit:F, descriptionText:Living Room Porch Vent was 79.3°F]
a1c077da-6008-40f2-b7b1-a517a6b6df9f 5:20:27 PM: debug description: temperature: 26.29
85e9dfe6-d385-4397-8de1-a628155c0e4e 5:20:27 PM: debug Parse returned [name:temperature, value:73, unit:F, linkText:Guest Bathroom Heater, descriptionText:Guest Bathroom Heater temperature is 73°F, isStateChange:false, displayed:false]
85e9dfe6-d385-4397-8de1-a628155c0e4e 5:20:27 PM: debug value 2300
85e9dfe6-d385-4397-8de1-a628155c0e4e 5:20:27 PM: debug Desc Map: [raw:F5C31902010A000029FC08, dni:F5C3, endpoint:19, cluster:0201, size:10, attrId:0000, result:success, encoding:29, value:08fc, isValidForDataType:true, clusterInt:513, attrInt:0]
85e9dfe6-d385-4397-8de1-a628155c0e4e 5:20:27 PM: debug Parse description read attr - raw: F5C31902010A000029FC08, dni: F5C3, endpoint: 19, cluster: 0201, size: 10, attrId: 0000, result: success, encoding: 29, value: 08fc
ea6a8804-7e59-48a5-a3a3-9cfb72f66167 5:20:20 PM: debug parsed event: [name:atmosphericPressure, value:101.0695, unit:kPa]
ea6a8804-7e59-48a5-a3a3-9cfb72f66167 5:20:20 PM: debug description: read attr - raw: DCF60104030C200022076C0F, dni: DCF6, endpoint: 01, cluster: 0403, size: 12, attrId: 0020, result: success, encoding: 22, value: 0f6c07

**Comment by KurtSanders** [comment]
I wish that I could be of assistance, but SmartThings has changed radically for the worse and I am now a happy Hubitat user & developer.  It pains me to have all my many years of Smartthings development and global support be wasted, but it is not a company or platform I wish to participate with, especially when they trample all over their dedicated developers and users.

The best advice I can provide is to migrate away from Samsung SmartThings, as IMHO, they are on the same downward vector as Atari, Blackberry, etc and eventually they will pull support for hosting ALL end user 'non certified' developed applications all together.
