### ISSUE TITLE
Smartthings integration with Ambient Weather

### ISSUE THREAD

**Issue by mikevelten** [KurtSanders/STAmbientWeather#27]
I know the ST interface is no longer supported but I was hoping the old version might work. Can anyone help with this error I get when I try to create a DTH in ST>

Groovy.lang.MissingMethodException: No signature of method: script_dth_metadata_c9abfa57_b340_4468_8733_a494ea50ff57.appSetting() is applicable for argument types: (java.lang.String) values: [apiKey] Possible solutions: typeSetting(java.lang.String), typeSetting(java.util.Map), typeSetting(java.lang.String, java.lang.String), getSettings(), setSettings(java.lang.Object), typeSetting(java.lang.String, java.lang.String, java.util.List)

**Comment by KurtSanders** [comment]
Unfortunately, this user developed app is no longer supported on ST.   I would recommend migrating to Hubitat which is a better home automation solution than ST.
