### ISSUE TITLE
API Error message: groovyx.net.http.HttpResponseException: status code: 401, reason phrase: Unauthorized

### ISSUE THREAD

**Issue by ZachGeb** [KurtSanders/STAmbientWeather#28]
I just started working with Hubitat.

During the installation I receive the following error
API Error message: groovyx.net.http.HttpResponseException: status code: 401, reason phrase: Unauthorized

I have copied over the API key as well as tried generating a few different ones. All result in the above error.

**Comment by KurtSanders** [comment]
A 401 error indicates an invalid Ambient API string.  If you provide your Ambient API string to kurt@kurtsanders.com I can check it to see that it is valid.
