### ISSUE TITLE
Warn Flood on Hubitat

### ISSUE THREAD

**Issue by sahaight** [KurtSanders/STAmbientWeather#29]
Once a minute I get this warning in my Hubitat log (the IP is for my Ambient Weather Station):

Received data from 192.168.0.162, no matching device found for 192.168.0.162, C0A800A2:321F, E09806A33362 or C0A800A2.

It's also odd that I get this every minute as I set it in the package manager to give me updates every 2 minutes.

**Comment by KurtSanders** [comment]
Dear sahaihjt,

That is an abnormal log message and not sure where this message originates from my code.  Can you confirm that it is being generated from my Ambient Weather app in the Hubitat Logs or possibly another Ambient Weather device driver that is not mine?  If it is from my Ambient Weather Station app, does this Hubitat log message stop generating messages if you pause or remove the Ambient Weather app?  

You might trying completely removing Ambient Weather Station from Hubitat Package Manager and then reinstalling from Hubitat Package Manager and then configuring the Ambient Weather Station app with your Ambient Weather Station API key?

**Comment by sahaight** [comment]
Well I'm not sure it's the app as I uninstalled it, reset the hub and still get the messages - the label is "sys:1".
However, I previously used another app that connected directly to the local weather station panel - cutting power to the panel stops the messages.  I only started getting these messages when I replace that one with yours. I had thought yours went through the web to Ambient Weather API and not through the local panel so it makes no sense to me.

Any ideas?

**Comment by KurtSanders** [comment]
My only advice is to: 

1. Check for a hubitat device or app that is still running on your Hubitat hub, perhaps, that is sending a http message directly to your 192.168.0.162 weather station and the weather station is responding with a return message which is not being handled by the hubitat hub?  If you find a device or app, remove it/them.  Reboot your Hubitat Hub.  
2. Perhaps unplug your Ambient weather station console and re-power it.  

_My Ambient Weather Station app only connects to Ambient weather's public API server and not to your local 192.168.0.162 network connected weather station._  

Sorry wish I had more sugesstions.

**Comment by sahaight** [comment]
Already did all of the above. My only thought is perhaps the old app registered with the local station but that wasn't cleared when I removed the app. I'll try reinitializing the station next I guess.

Thanks anyway.

**Comment by sahaight** [comment]
Figured it out - connection was set up in the awnet android app. I disabled it there.

**Comment by KurtSanders** [comment]
Good thinking and that is a possibility that your weather station is responding back via http every minute to the Hubitat hub with your weather station data and the Hubitat hub no longer has that weather device.  It cannot relay the http packet and throw a sys error.  Hope that is it!

**Comment by KurtSanders** [comment]
Great thinking!
