### ISSUE TITLE
Release 6.1.0 missing in HPM

### ISSUE THREAD

**Issue by klieber** [KurtSanders/STAmbientWeather#30]
According to the release notes, the latest release is 6.1.0. However, HPM seems to only install 6.0.0. I also looked at the app / driver code in this repo and it doesn't appear to have been updated either. I'm wondering if there is a change that never got pushed?

https://github.com/KurtSanders/STAmbientWeather/wiki/Features-by-Version

**Comment by KurtSanders** [comment]
Good catch, and yes, I will push this release into HPM this week.  I was testing with my weather station for several weeks to try to catch any bugs with all the changes that I made in this release!

**Comment by KurtSanders** [comment]
Version 6.1.0 has been added to HPM and a new [Hubitat Community Thread](https://community.hubitat.com/t/release-ambient-weather-station-app/128838) has been created.
