### ISSUE TITLE
groovyx.net.http.HttpResponseException: Unauthorized

### ISSUE THREAD

**Issue by lightswitch05** [KurtSanders/STAmbientWeather#5]
I setup the apiKey in the application before publishing it. 

![image](https://user-images.githubusercontent.com/598803/51283532-7e95ce80-19b6-11e9-9c9f-25fdecb07821.png)

App keeps saying that setup is incomplete

![image](https://user-images.githubusercontent.com/598803/51283606-c0bf1000-19b6-11e9-976f-f216c842c1f1.png)

Live Logging shows that its trying, but that its getting an `Unauthorized` failure

![image](https://user-images.githubusercontent.com/598803/51283672-fcf27080-19b6-11e9-8343-4058d594fe57.png)

**Comment by lightswitch05** [comment]
Creating a second API key fixed the issue for the first API key. It must be some sort of consistency issue on Ambient Weather's side.

**Comment by lightswitch05** [comment]
Its all setup and running now. This is a very nice SmartApp, thanks!

**Comment by KurtSanders** [comment]
Glad to hear... thanks!
