### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke method sendEvent() on null object

### ISSUE THREAD

**Issue by eugeniousone** [KurtSanders/STAmbientWeather#7]
java.lang.NullPointerException: Cannot invoke method sendEvent() on null object @line 439 (ambientWeatherStation)

I get this when I am trying to add all of the initial information in the app.  It says that it saved, then throws this exception.

**Comment by KurtSanders** [comment]
That program line, in the current version on github,  has to do with "lastRain" which some Ambient weather stations do not support.  I have program logic to ignore that line of code if the Ambient API does not return that field.  So I am scratching my head.  

I may need to get access to your Ambient API key to test and debug what is being returned from your weather station.  Do you have a [SmartThings Community Forum](https://community.smartthings.com/) account where we can start a Private Message (PM).  My username is kurtsanders and you can securely send your Ambient API so I can investigate.

**Comment by KurtSanders** [comment]
Dear eugeniousone,

I have a beta branch in this repo for you to test on SmartThings that attempts to eliminate this error you are receiving during install, but without your Ambient API key for temporary testing, I am unable to verify what is causing your unique issue.  

If you would temporarily share your Ambient Weather API key via a secure PM on http://community.smartthings.com I can do more extensive testing with your configuration.  If you do not wish to share, I can only try a few things.  My username is the same here as it is on the http://community.smartthings.com website.

**Comment by eugeniousone** [comment]
Sure, I can pvt you my API key, no problem.  Ju

**Comment by KurtSanders** [comment]
Still have not received your API via http://community.smartthings.com .  Would you rather send via email?

**Comment by eugeniousone** [comment]
Sorry, yes please since I just cannot figure out how to post a pm through SmartThings.

Sincerely,

Eugene Brink

**Comment by KurtSanders** [comment]
API Key received..  investigating

**Comment by KurtSanders** [comment]
Confirmed working in V4.0.0 with users PI key.  Issue Resolved.
